name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        uses: ilteoood/docker_buildx@master
        with:
          publish: false
          imageName: mozillaiot/gateway
          platform: linux/amd64,linux/arm/v7,linux/arm64
